apiVersion: apps/v1
kind: Deployment
metadata:
  name: finalproject-deployment
  namespace: ivolve
  labels:
    app: finalproject-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finalproject-deployment
  template:
    metadata:
      labels:
        app: finalproject-deployment
    spec:
      containers:
      - name: finalproject
        image: belal90/finalproject:latest
        ports:
        - containerPort: 5000
